leftnav:
- identifier: 8a9fb450-4eb3-406c-216f-374a8edf8495
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: a9e81c82-e9eb-0e45-eb5f-8a8a8e4cfae6
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: e324d496-83ac-95b1-0b6e-16707707c20b
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: 548b59fc-4da4-9c58-5555-d49a0b05fe43
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 40
- identifier: bd8c6dc1-8fa1-d820-1ba1-155dbbbf3cdf
  name: Projects
  pageRef: /pages/projects
  weight: 50
